# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(737, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        MainWindow.setFocusPolicy(QtCore.Qt.TabFocus)
        MainWindow.setWindowOpacity(0.9)
        MainWindow.setToolTip("")
        MainWindow.setAutoFillBackground(True)

        #central widget
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(60, 20, 631, 21))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)

        #create labels
        self.label.setFont(font)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 60, 631, 21))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 90, 631, 21))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setScaledContents(False)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 130, 631, 21))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setScaledContents(False)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.plainText1_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.plainText1_label.setFont(font)
        self.plainText1_label.setObjectName("plainText1_label")
        self.plainText1_input = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainText1_input.setFont(font)
        self.plainText1_input.setObjectName("plainText1_input")
        self.key_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.key_label.setFont(font)
        self.key_label.setObjectName("key_label")
        self.key_input = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)

        #create input fields
        self.key_input.setFont(font)
        self.key_input.setObjectName("key_input")
        self.plainText2_input = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainText2_input.setFont(font)
        self.plainText2_input.setObjectName("plainText2_input")
        self.chiper_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.chiper_label.setFont(font)
        self.chiper_label.setObjectName("chiper_label")
        self.plainText2_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.plainText2_label.setFont(font)
        self.plainText2_label.setObjectName("plainText2_label")
        self.chiper_input = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.chiper_input.setFont(font)
        self.chiper_input.setObjectName("chiper_input")

        #create buttons
        self.bersihkan_btn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft Himalaya")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.bersihkan_btn.setFont(font)
        self.bersihkan_btn.setObjectName("bersihkan_btn")
        self.dekripsi_btn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft Himalaya")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.dekripsi_btn.setFont(font)
        self.dekripsi_btn.setObjectName("dekripsi_btn")
        self.enkripsi_btn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft Himalaya")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.enkripsi_btn.setFont(font)
        self.enkripsi_btn.setObjectName("enkripsi_btn")

        #set central widget
        MainWindow.setCentralWidget(self.centralwidget)

        #create menubar
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 737, 21))
        self.menubar.setObjectName("menubar")

        #create menus
        self.menuOpsi = QtWidgets.QMenu(self.menubar)
        self.menuOpsi.setTitle("Opsi")

        self.menuBantuan = QtWidgets.QMenu(self.menubar)
        self.menuBantuan.setTitle("Bantuan")

        #add menu to menu bar
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuOpsi.menuAction())
        self.menubar.addAction(self.menuBantuan.menuAction())
        

        # Connect signals and slots
        MainWindow.setWindowTitle("VIGENERE SHIPER")
        self.show_encrypt_ui(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Actions
        self.actionEncrypt = QtWidgets.QAction(MainWindow)
        self.actionEncrypt.setText("Enkripsi")
        self.actionEncrypt.triggered.connect(self.show_encrypt_ui)

        self.actionDecrypt = QtWidgets.QAction(MainWindow)
        self.actionDecrypt.setText("Dekripsi")
        self.actionDecrypt.triggered.connect(self.show_decrypt_ui)

        # Tambahkan teks bantuan langsung dalam metode setupUi
        help_message = "Ini adalah aplikasi Vigenere Cipher untuk enkripsi dan dekripsi teks. " \
                    "Silakan masukkan teks di kolom Plain Text dan key di kolom Key. " \
                    "Pilih menu Opsi -> Encrypt untuk melakukan enkripsi atau Decrypt untuk dekripsi."
        self.menuBantuan.aboutToShow.connect(lambda: QtWidgets.QMessageBox.information(MainWindow, "Petunjuk Penggunaan", help_message))

        # Add actions to menus
        self.menuOpsi.addAction(self.actionEncrypt)
        self.menuOpsi.addAction(self.actionDecrypt)

        # Connect the buttons to their respective functions
        self.enkripsi_btn.clicked.connect(self.encrypt)
        self.dekripsi_btn.clicked.connect(self.decrypt)
        self.bersihkan_btn.clicked.connect(self.clear_text)

        # Other
        self.label_2.setText("MATA KULIAH KRIPTOGRAFI DAN KEAMANAN SISTEM")
        self.label_3.setText("APLIKASI VIGENERE CHIPER")
        self.label_4.setText("OLEH : MUH. FATTA NUR RAZAQ - C2C021048")


    def show_encrypt_ui(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate

        self.label.setText("TUGAS 3-Enkripsi")

        self.clear_text()

        self.plainText1_label.setText(_translate("MainWindow", "PLAIN TEXT :"))
        self.plainText1_label.setGeometry(QtCore.QRect(120, 200, 121, 20))
        self.plainText1_input.setGeometry(QtCore.QRect(260, 200, 201, 20))
        
        self.key_label.setText(_translate("MainWindow", "KEY :"))
        self.key_label.setGeometry(QtCore.QRect(120, 240, 121, 20))
        self.key_input.setGeometry(QtCore.QRect(260, 240, 201, 20))


        self.chiper_label.setText(_translate("MainWindow", "CHIPER TEXT :"))
        self.chiper_label.setGeometry(QtCore.QRect(120, 280, 121, 20))
        self.chiper_input.setGeometry(QtCore.QRect(260, 280, 201, 20))

        self.bersihkan_btn.setText(_translate("MainWindow", "BERSIHKAN"))
        self.enkripsi_btn.setText(_translate("MainWindow", "ENKRIPSI"))
        
        self.enkripsi_btn.setGeometry(QtCore.QRect(530, 240, 101, 23))
        self.bersihkan_btn.setGeometry(QtCore.QRect(530, 280, 101, 23))

        # Untuk membuat input tidak bisa diedit
        self.chiper_input.setReadOnly(True)

        # show and hide
        self.enkripsi_btn.show()
        self.dekripsi_btn.hide()
        self.plainText2_label.hide()
        self.plainText2_input.hide()
        self.plainText1_label.show()
        self.plainText1_input.show()




    def show_decrypt_ui(self):
        _translate = QtCore.QCoreApplication.translate
        
        self.clear_text()

        self.label.setText(_translate("MainWindow", "TUGAS 3-Dekripsi"))

        self.chiper_label.setText(_translate("MainWindow", "CHIPER TEKS :"))
        self.chiper_label.setGeometry(QtCore.QRect(120, 200, 121, 20))
        self.chiper_input.setGeometry(QtCore.QRect(260, 200, 201, 20))       

        self.key_label.setText(_translate("MainWindow", "KEY :"))
        self.key_label.setGeometry(QtCore.QRect(120, 240, 121, 20))
        self.key_input.setGeometry(QtCore.QRect(260, 240, 201, 20))

        self.plainText2_label.setText(_translate("MainWindow", "DEKRIPSI :"))
        self.plainText2_label.setGeometry(QtCore.QRect(120, 280, 121, 20))
        self.plainText2_input.setGeometry(QtCore.QRect(260, 280, 201, 20))        

        self.bersihkan_btn.setText(_translate("MainWindow", "BERSIHKAN"))
        self.dekripsi_btn.setText(_translate("MainWindow", "DEKRIPSI"))

        self.dekripsi_btn.setGeometry(QtCore.QRect(530, 240, 101, 23))

        # Untuk membuat input tidak bisa diedit
        self.chiper_input.setReadOnly(False)
        self.plainText2_input.setReadOnly(True)

        self.dekripsi_btn.show()
        self.enkripsi_btn.hide()
        self.plainText2_label.show()
        self.plainText2_input.show()
        self.plainText1_label.hide()
        self.plainText1_input.hide()


    def encrypt(self):
        plain_text = self.plainText1_input.text().upper()
        key = self.key_input.text().upper()

        encrypted_text = ""
        key_index = 0

        for char in plain_text:
            if char.isalpha():
                shift = ord(key[key_index]) - ord('A')
                encrypted_text += chr((ord(char) + shift - 65) % 26 + 65)
                key_index = (key_index + 1) % len(key)
            else:
                encrypted_text += char

            self.chiper_input.setText(encrypted_text)
    
    def decrypt(self):
        cipher_text = self.chiper_input.text().upper()
        key = self.key_input.text().upper()

        decrypted_text = ""
        key_index = 0

        for char in cipher_text:
            if char.isalpha():
                shift = ord(key[key_index]) - ord('A')
                decrypted_text += chr((ord(char) - shift - 65) % 26 + 65)
                key_index = (key_index + 1) % len(key)
            else:
                decrypted_text += char

        self.plainText2_input.setText(decrypted_text)

    def clear_text(self):
        self.plainText1_input.clear()
        self.key_input.clear()
        self.chiper_input.clear()
        self.plainText2_input.clear()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
